#!/bin/bash

# git-ps1 from https://github.com/mikegerwitz/git-supp
git_supp=${GIT_SUPP:-$HOME/build/git-supp}

if [ -d "$git_supp" ]; then
  export GITPS1_IND_STAGED='✓'
  export GITPS1_IND_UNSTAGED='◊'
  export GITPS1_IND_UNTRACKED='∅'
  export GITPS1_IND_AHEAD='↑'
  export GITPS1_COLOR_DEFAULT=33
  export GITPS1_COLOR_FASTFWD=36
  export GITPS1_COLOR_STAGED=32
  export GITPS1_COLOR_UNTRACKED=31
  export GITPS1_COLOR_UNSTAGED=35
  export GITPS1_COLOR_AHEAD=34
  export GITPS1_COLOR_STATE=37
  gitps1="\$($( cat "$git_supp/git-ps1.sh" ))"
fi

# ripped from git-ps1 source
mkcolor() {
  echo "\[\033[00;$1m\]"
}
clear=$(mkcolor 0)
black=$(mkcolor 30)
red=$(mkcolor 31)
green=$(mkcolor 32)
yellow=$(mkcolor 33)
blue=$(mkcolor 34)
magenta=$(mkcolor 35)
cyan=$(mkcolor 36)
white=$(mkcolor 37)

last_error() {
  last=$?
  if [ "$last" -ne 0 ]; then
    echo "✗$last "
  fi
}

last_error="${red}\$(last_error)${clear}"
datetime="${green}\D{%-e-%b} ${cyan}\t${clear}"
cwd="${magenta}\W${clear}"
export PS1="$last_error$datetime$gitps1 $cwd $blue\n\$ $clear"
