#!/bin/bash

alias b=bundle
alias be='bundle exec'
alias brake='bundle exec rake'
alias brails='bundle exec rails'

eval "$(rbenv init -)"

# prefix=$(brew --prefix)
# # chruby from homebrew
# source "$prefix/opt/chruby/share/chruby/chruby.sh"
# source "$prefix/opt/chruby/share/chruby/auto.sh"
